# Generated by Django 6.0.2 on 2026-02-17 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=100, unique=True, verbose_name='ID в Instagram')),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(max_length=20)),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('permalink', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=100, unique=True, verbose_name='ID комментария в Instagram')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('username', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram.post')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
