# Generated by Django 6.0.2 on 2026-02-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='permalink',
            field=models.URLField(max_length=2000),
        ),
    ]
